# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # todo: apply new java code in the github actions

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        working-directory: ./stats-collector
        run: mvn -B package --file pom.xml

      - name: Run reports
        working-directory: ./stats-collector
        run: |
          mkdir -p /tmp/workingdir/netcracker
          cp ./target/stats-collector.jar /tmp/workingdir/stats-collector.jar
          cd /tmp/workingdir/netcracker
          curl "https://api.github.com/orgs/Netcracker/repos?per_page=500" | grep -e 'clone_url*' | cut -d \" -f 4 | xargs -L1 git clone
          cd ..
          java -jar stats-collector.jar /tmp/workingdir/netcracker

      - uses: actions/checkout@v4
      - name: Do commit back to repo
        run: |
          date=$(date +"%d-%m-%Y-%H-%M-%S")
          cp /tmp/workingdir/netcracker/combined-report.json ./reports-are-here/json/combined-report-$date.json
          cp /tmp/workingdir/netcracker/combined-report.md ./reports-are-here/combined-report-$date.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./reports-are-here/json/combined-report-$date.json
          git add ./reports-are-here/combined-report-$date.md
          git commit -m "generated"
          git push