# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # note - time in UTC
  schedule:
    - cron: "15 2 * * *"

  # todo: apply new java code in the github actions

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        working-directory: ./stats-collector
        run: mvn -B package --file pom.xml

      - name: Run reports
        working-directory: ./stats-collector
        run: |
          mkdir -p /tmp/workingdir/netcracker
          mkdir -p /tmp/workingdir/docs
          cp ./../docs/template.html /tmp/workingdir/docs/template.html
          cp ./../clone_all.sh /tmp/workingdir/netcracker/clone_all.sh
          cp ./target/stats-collector.jar /tmp/workingdir/stats-collector.jar
          
          mkdir -p ./../reports-are-here/data
          mkdir -p /tmp/workingdir/netcracker/data
          cp -r ./../reports-are-here/data /tmp/workingdir/netcracker/data
          
          cd /tmp/workingdir/netcracker
          sudo chmod +x clone_all.sh
          sudo ./clone_all.sh
        
          cd /tmp/workingdir
          sudo java -jar stats-collector.jar /tmp/workingdir/netcracker

      - uses: actions/checkout@v4
      - name: Do commit back to repo
        run: |
          date=$(date +"%d-%m-%Y-%H-%M-%S")
          sed -i -e "s/#GEN_DATE#/$date/g" /tmp/workingdir/netcracker/combined-report.html           
          cp /tmp/workingdir/netcracker/persisted-data.json ./reports-are-here/data/persisted-data-$date.json
          cp /tmp/workingdir/netcracker/combined-report.html ./reports-are-here/combined-report-$date.html
          cp /tmp/workingdir/netcracker/combined-report.html ./docs/index.html
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./reports-are-here/data/persisted-data-$date.json
          git add ./reports-are-here/combined-report-$date.html
          git add ./docs/index.html
          git commit -m "HTML report generation at $date"
          git push
